# Generated by Django 4.2.9 on 2024-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_birdspecies_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='common_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='status_code',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], max_length=2),
        ),
    ]
