# Generated by Django 4.2.9 on 2024-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_birdspecies_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='status_code',
            field=models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], max_length=2, null=True),
        ),
    ]
