# Generated by Django 4.2.9 on 2024-01-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_birdspecies_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
