# Generated by Django 4.2.9 on 2024-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_birdspecies_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='bird_description',
            field=models.TextField(blank=True, default='default_value', null=True),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='common_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='current_status',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], max_length=10),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
    ]
