# Generated by Django 4.2.9 on 2024-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_birdspecies_bird_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='scientific_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
