# Generated by Django 4.2.9 on 2024-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_birdspecies_scientific_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdspecies',
            name='bird_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='birdspecies',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
    ]
